name: Build and Release (Simple)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Build release files (no publish)
      run: npm run dist:win:no-publish

    - name: Generate latest.yml
      run: npm run generate-latest-yml

    - name: Verify release files
      run: |
        Write-Host "=== Release Files Verification ==="
        Write-Host "Release directory contents:"
        Get-ChildItem -Path "release" -Force | Format-Table Name, Length, LastWriteTime
        
        Write-Host "`nChecking latest.yml:"
        if (Test-Path "release/latest.yml") {
          Write-Host "✅ latest.yml exists"
          $content = Get-Content "release/latest.yml" -Raw
          Write-Host "Content preview:"
          Write-Host $content.Substring(0, [Math]::Min(200, $content.Length))
        } else {
          Write-Host "❌ latest.yml not found"
        }
        
        Write-Host "`nChecking BtwBuddy-Setup.exe:"
        if (Test-Path "release/BtwBuddy-Setup.exe") {
          $file = Get-ChildItem "release/BtwBuddy-Setup.exe"
          Write-Host "✅ BtwBuddy-Setup.exe exists"
          Write-Host "Size: $([math]::Round($file.Length / 1MB, 2)) MB"
          Write-Host "Modified: $($file.LastWriteTime)"
        } else {
          Write-Host "❌ BtwBuddy-Setup.exe not found"
        }
      shell: pwsh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/latest.yml
          release/BtwBuddy-Setup.exe
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## 🚀 BtwBuddy Release
          
          ### 📦 What's included:
          - **latest.yml**: Auto-updater configuration
          - **BtwBuddy-Setup.exe**: Windows installer
          
          ### 🔧 Installation:
          1. Download and run `BtwBuddy-Setup.exe`
          2. Follow the installation wizard
          3. The app will automatically check for updates
          
          ### 📋 Manual Updates:
          If auto-updates don't work, use the built-in Version Manager:
          1. Open BtwBuddy
          2. Go to Settings → Ontwikkelaar Tools → Open Versie Beheer
          3. Select and download any version manually
          
          ### 🔍 Troubleshooting:
          - If auto-updater fails, use the Version Manager
          - Check logs in `%APPDATA%/BtwBuddy/logs/`
          - Manual downloads available via Version Manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 